#!/usr/bin/expect
set timeout 2400
set username_host [lindex $argv 0]
#set password [lindex $argv 1]
set src_file [lindex $argv 1]
set dest_file [lindex $argv 2]
 
spawn scp $username_host:$src_file $dest_file
expect {
    "(yes/no)?"
        {
            send "yes\n"
            expect "*assword:" { send "$password\n"}
        }
#    "*assword:"
#        {
#            send "$password\n"
#        }
    } 
interact
