curl -v spider1-dbn.rhcloud.com &
curl -v spider2-dbn.rhcloud.com &
curl -v spider3-dbn.rhcloud.com &
curl -v spider1-dbn1.rhcloud.com &
curl -v spider2-dbn1.rhcloud.com &
curl -v spider3-dbn1.rhcloud.com &
curl -v spider1-dbn2.rhcloud.com &
curl -v spider2-dbn2.rhcloud.com &
curl -v spider3-dbn2.rhcloud.com &
curl -v spider1-dbn3.rhcloud.com &
curl -v spider2-dbn3.rhcloud.com &
curl -v spider3-dbn3.rhcloud.com &
curl -v spider13-dbn5.rhcloud.com &
curl -v spider14-dbn5.rhcloud.com &
curl -v spider15-dbn5.rhcloud.com &
curl -v spider16-dbn6.rhcloud.com &
curl -v spider17-dbn6.rhcloud.com &
curl -v spider18-dbn6.rhcloud.com &
curl -v spider19-dbn7.rhcloud.com &
curl -v spider20-dbn7.rhcloud.com &
curl -v spider21-dbn7.rhcloud.com &
curl -v spider22-dbn8.rhcloud.com &
curl -v spider23-dbn8.rhcloud.com &
curl -v spider24-dbn8.rhcloud.com &
curl -v spider25-dbn9.rhcloud.com &
curl -v spider26-dbn9.rhcloud.com &
curl -v spider27-dbn9.rhcloud.com &
curl -v spider28-dbn10.rhcloud.com &
curl -v spider29-dbn10.rhcloud.com &
curl -v spider30-dbn10.rhcloud.com &
